packages:
  - '.'
  - 'js_libraries/*'
  - devtool/base_devtool/js_libraries/logbox-types
  - devtool/base_devtool/js_libraries/logbox
  - devtool/lynx_devtool/resources/devtool-switch
  - devtool/lynx_devtool/resources/lynx-error-parser
  - explorer
  - explorer/lib
  - explorer/homepage
  - explorer/showcase
  - explorer/showcase/menu
  - explorer/showcase/jank
  # base devtool
  - 'lynx/devtool/base_devtool/js_libraries/logbox'
  - tools/api/parser/ts_morph
  - third_party/weak-node-api
  # e2e dependencies
  - testing/integration_test/test_script

catalog:
  '@lynx-js/qrcode-rsbuild-plugin': '0.3.6'
  '@lynx-js/rspeedy': '0.9.3'
  '@lynx-js/react': '0.107.0'
  '@lynx-js/react-rsbuild-plugin': '0.9.8'
  '@lynx-js/types': '3.3.0'
  '@types/react': '18.3.18'
